# Generated by Django 5.1.6 on 2026-04-11 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticItem',
            fields=[
                ('CosmeticID', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('ItemName', models.CharField(default='DefaultItemName', max_length=255, unique=True)),
                ('ItemType', models.CharField(choices=[('Hat', 'Hat'), ('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Glasses', 'Glasses'), ('Shoes', 'Shoes')], default='Hat', max_length=50)),
                ('Cost', models.PositiveIntegerField(default=1)),
                ('ImagePath', models.ImageField(default='default_img.jpeg', upload_to='cosmetics/')),
            ],
        ),
        migrations.CreateModel(
            name='UserCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsEquipped', models.BooleanField(default=False)),
                ('DatePurchased', models.DateTimeField(auto_now_add=True)),
                ('CosmeticID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='cosmetics.cosmeticitem')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cosmetics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UserID', 'CosmeticID')},
            },
        ),
    ]
