# Generated by Django 5.1.6 on 2026-04-13 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticItem',
            fields=[
                ('cosmeticID', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('cost', models.PositiveIntegerField(default=10)),
                ('image', models.ImageField(upload_to='cosmetics/avatars/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='cosmetics/previews/')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
                ('equipped_cosmetic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosmetics.cosmeticitem')),
            ],
        ),
        migrations.CreateModel(
            name='UserCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('cosmeticID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='cosmetics.cosmeticitem')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userID', 'cosmeticID')},
            },
        ),
    ]
