# Generated by Django 5.1.6 on 2026-04-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='trophy', max_length=50)),
                ('criteria', models.CharField(max_length=50)),
                ('threshold', models.IntegerField(default=1)),
                ('multiplayer_only', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('solo', 'Solo'), ('multiplayer', 'Multiplayer'), ('general', 'General')], default='general', max_length=20)),
                ('is_hidden', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=10)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('answer_given', models.CharField(blank=True, max_length=255)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('solo', 'Solo'), ('multiplayer', 'Multiplayer')], default='multiplayer', max_length=12)),
            ],
            options={
                'ordering': ['-answered_at'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=1)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards_studied', models.PositiveIntegerField(default=0)),
                ('total_decks_completed', models.PositiveIntegerField(default=0)),
                ('total_games_played', models.PositiveIntegerField(default=0)),
                ('total_games_won', models.PositiveIntegerField(default=0)),
                ('total_correct_answers', models.PositiveIntegerField(default=0)),
                ('total_answers', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('multiplayer_games_played', models.PositiveIntegerField(default=0)),
                ('multiplayer_games_won', models.PositiveIntegerField(default=0)),
                ('solo_sessions_completed', models.PositiveIntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('consecutive_study_days', models.PositiveIntegerField(default=0)),
                ('best_consecutive_study_days', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'user stats',
            },
        ),
    ]
