# Generated by Django 5.0.4 on 2026-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
