# Generated by Django 6.0.2 on 2026-04-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_sr_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='cards_mastered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='spaced_repetition_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
