# Generated by Django 5.1.6 on 2026-04-13 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('DeckID', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('DeckName', models.CharField(default='None', max_length=20)),
                ('Description', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('Category', models.CharField(blank=True, default='None', max_length=20, null=True)),
                ('IsPublic', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_studied', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeckSettings',
            fields=[
                ('DeckID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='deck.deck')),
                ('MaxNewPerDay', models.PositiveIntegerField(default=20, help_text='Maximum new cards to introduce per day')),
                ('MaxLearningPerDay', models.PositiveIntegerField(default=20, help_text='Maximum learning cards to study per day')),
                ('MaxReviewPerDay', models.PositiveIntegerField(default=100, help_text='Maximum review cards to study per day')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('CardID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(default='None', max_length=255)),
                ('Answer', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('QuestionImage', models.ImageField(blank=True, null=True, upload_to='card_images/')),
                ('AnswerImage', models.ImageField(blank=True, null=True, upload_to='card_images/')),
                ('FlashDateCreated', models.DateTimeField(auto_now_add=True)),
                ('LastReviewed', models.DateTimeField(auto_now=True)),
                ('DeckID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='deck.deck')),
            ],
        ),
        migrations.CreateModel(
            name='DeckDailyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('NewStudied', models.PositiveIntegerField(default=0)),
                ('LearningStudied', models.PositiveIntegerField(default=0)),
                ('ReviewStudied', models.PositiveIntegerField(default=0)),
                ('DeckID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_counts', to='deck.deck')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UserID', 'DeckID', 'Date')},
            },
        ),
        migrations.CreateModel(
            name='CardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], default='new', max_length=12)),
                ('EF', models.FloatField(default=2.5, help_text='Easiness factor (min 1.3, starts at 2.5)')),
                ('Repetitions', models.PositiveIntegerField(default=0, help_text='Consecutive successful recalls in review state')),
                ('Interval', models.FloatField(default=0, help_text='Current interval in days (0 = not yet scheduled)')),
                ('StepIndex', models.PositiveIntegerField(default=0, help_text='Current index within learning/relearning steps')),
                ('NextReview', models.DateTimeField(blank=True, help_text='When card is due next (null = due now)', null=True)),
                ('LastReviewed', models.DateTimeField(blank=True, help_text='Timestamp of most recent review', null=True)),
                ('Mastered', models.BooleanField(default=False)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_card_progress', to=settings.AUTH_USER_MODEL)),
                ('CardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to='deck.flashcard')),
            ],
            options={
                'unique_together': {('UserID', 'CardID')},
            },
        ),
    ]
