# Generated by Django 5.1.6 on 2026-04-11 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('DeckID', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('DeckName', models.CharField(default='None', max_length=20)),
                ('Description', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('Category', models.CharField(blank=True, default='None', max_length=20, null=True)),
                ('IsPublic', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_studied', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('CardID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(default='None', max_length=255)),
                ('Answer', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('FlashDateCreated', models.DateTimeField(auto_now_add=True)),
                ('LastReviewed', models.DateTimeField(auto_now=True)),
                ('DeckID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='deck.deck')),
            ],
        ),
        migrations.CreateModel(
            name='CardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult'), ('Very Difficult', 'Very Difficult')], default='Medium', max_length=20)),
                ('TimesReviewed', models.PositiveIntegerField(default=0)),
                ('NextReviewDate', models.DateTimeField(auto_now_add=True)),
                ('LastReviewDate', models.DateTimeField(auto_now_add=True)),
                ('Mastered', models.BooleanField(default=False)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_card_progress', to=settings.AUTH_USER_MODEL)),
                ('CardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to='deck.flashcard')),
            ],
            options={
                'unique_together': {('UserID', 'CardID')},
            },
        ),
    ]
