# Generated by Django 5.0.4 on 2026-04-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='AnswerImage',
            field=models.ImageField(blank=True, null=True, upload_to='card_images/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='QuestionImage',
            field=models.ImageField(blank=True, null=True, upload_to='card_images/'),
        ),
    ]
