# Generated by Django 5.1.6 on 2026-03-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='deck',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='cardprogress',
            name='UserID',
        ),
    ]
