# Generated by Django 6.0.2 on 2026-04-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_user'),
        ('deck', '0002_alter_cardprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprogress',
            name='UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_card_progress', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_decks', to='api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardprogress',
            name='Difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult'), ('Very Difficult', 'Very Difficult')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='cardprogress',
            unique_together={('UserID', 'CardID')},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
