# Generated by Django 6.0.2 on 2026-04-09 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_alter_cardprogress_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardprogress',
            unique_together={('UserID', 'CardID')},
        ),
    ]
