# Generated by Django 6.0.2 on 2026-04-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_alter_cardprogress_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardprogress',
            name='Difficulty',
        ),
        migrations.RemoveField(
            model_name='cardprogress',
            name='LastReviewDate',
        ),
        migrations.RemoveField(
            model_name='cardprogress',
            name='NextReviewDate',
        ),
        migrations.RemoveField(
            model_name='cardprogress',
            name='TimesReviewed',
        ),
        migrations.AddField(
            model_name='cardprogress',
            name='EF',
            field=models.FloatField(default=2.5, help_text='Easiness factor (min 1.3, starts at 2.5)'),
        ),
        migrations.AddField(
            model_name='cardprogress',
            name='Interval',
            field=models.FloatField(default=0, help_text='Current interval in days (0 = not yet scheduled)'),
        ),
        migrations.AddField(
            model_name='cardprogress',
            name='LastReviewed',
            field=models.DateTimeField(blank=True, help_text='Timestamp of most recent review', null=True),
        ),
        migrations.AddField(
            model_name='cardprogress',
            name='NextReview',
            field=models.DateTimeField(blank=True, help_text='When card is due next (null = due now)', null=True),
        ),
        migrations.AddField(
            model_name='cardprogress',
            name='Repetitions',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive successful recalls in review state'),
        ),
        migrations.AddField(
            model_name='cardprogress',
            name='State',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('relearning', 'Relearning')], default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='cardprogress',
            name='StepIndex',
            field=models.PositiveIntegerField(default=0, help_text='Current index within learning/relearning steps'),
        ),
    ]
