# Generated by Django 6.0.2 on 2026-04-10 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0004_remove_cardprogress_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckSettings',
            fields=[
                ('DeckID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='deck.deck')),
                ('MaxNewPerDay', models.PositiveIntegerField(default=20, help_text='Maximum new cards to introduce per day')),
                ('MaxLearningPerDay', models.PositiveIntegerField(default=20, help_text='Maximum learning cards to study per day')),
                ('MaxReviewPerDay', models.PositiveIntegerField(default=100, help_text='Maximum review cards to study per day')),
            ],
        ),
        migrations.CreateModel(
            name='DeckDailyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('NewStudied', models.PositiveIntegerField(default=0)),
                ('LearningStudied', models.PositiveIntegerField(default=0)),
                ('ReviewStudied', models.PositiveIntegerField(default=0)),
                ('DeckID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_counts', to='deck.deck')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UserID', 'DeckID', 'Date')},
            },
        ),
    ]
