# Generated by Django 6.0.2 on 2026-04-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_alter_profile_user'),
        ('deck', '0003_cardprogress_userid_deck_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerRoom',
            fields=[
                ('RoomID', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('RoomCode', models.CharField(max_length=10, unique=True)),
                ('Status', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('Deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.deck')),
                ('Host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField(default=0)),
                ('JoinedAt', models.DateTimeField(auto_now_add=True)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='multiplayer.multiplayerroom')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('Room', 'User')},
            },
        ),
    ]
