# Generated by Django 6.0.2 on 2026-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayerroom',
            name='CardOrder',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='multiplayerroom',
            name='CurrentCardIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='multiplayerroom',
            name='TotalRounds',
            field=models.IntegerField(default=10),
        ),
    ]
