# Generated by Django 6.0.2 on 2026-04-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0002_multiplayerroom_cardorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='CurrentCardSubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
