# Generated by Django 6.0.2 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0003_roomparticipant_currentcardsubmitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
    ]