# Generated by Django 6.0.2 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0004_roomparticipant_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='LastAnswerCorrect',
            field=models.BooleanField(null=True, blank=True),
        ),
    ]
